export const typeColors: Record<string, string> = {
  normal: "bg-gray-400",
  fire: "bg-red-500",
  water: "bg-blue-500",
  electric: "bg-yellow-500",
  grass: "bg-green-500",
  ice: "bg-cyan-400",
  fighting: "bg-red-700",
  poison: "bg-purple-500",
  ground: "bg-yellow-600",
  flying: "bg-indigo-400",
  psychic: "bg-pink-500",
  bug: "bg-green-400",
  rock: "bg-yellow-800",
  ghost: "bg-purple-700",
  dragon: "bg-purple-600",
  dark: "bg-gray-800",
  steel: "bg-gray-500",
  fairy: "bg-pink-300",
}

export const typeChart: Record<string, { strong: string[]; weak: string[]; immune?: string[] }> = {
  fire: { strong: ["grass", "ice", "bug", "steel"], weak: ["water", "ground", "rock"] },
  water: { strong: ["fire", "ground", "rock"], weak: ["grass", "electric"] },
  grass: { strong: ["water", "ground", "rock"], weak: ["fire", "ice", "poison", "flying", "bug"] },
  electric: { strong: ["water", "flying"], weak: ["ground"], immune: ["ground"] },
  psychic: { strong: ["fighting", "poison"], weak: ["bug", "ghost", "dark"], immune: ["dark"] },
  ice: { strong: ["grass", "ground", "flying", "dragon"], weak: ["fire", "fighting", "rock", "steel"] },
  dragon: { strong: ["dragon"], weak: ["ice", "dragon", "fairy"], immune: ["fairy"] },
  dark: { strong: ["psychic", "ghost"], weak: ["fighting", "bug", "fairy"] },
  fairy: { strong: ["fighting", "dragon", "dark"], weak: ["poison", "steel"] },
  fighting: {
    strong: ["normal", "ice", "rock", "dark", "steel"],
    weak: ["flying", "psychic", "fairy"],
    immune: ["ghost"],
  },
  poison: { strong: ["grass", "fairy"], weak: ["ground", "psychic"] },
  ground: {
    strong: ["fire", "electric", "poison", "rock", "steel"],
    weak: ["water", "grass", "ice"],
    immune: ["flying"],
  },
  flying: { strong: ["grass", "fighting", "bug"], weak: ["electric", "ice", "rock"] },
  bug: { strong: ["grass", "psychic", "dark"], weak: ["fire", "flying", "rock"] },
  rock: { strong: ["fire", "ice", "flying", "bug"], weak: ["water", "grass", "fighting", "ground", "steel"] },
  ghost: { strong: ["psychic", "ghost"], weak: ["ghost", "dark"], immune: ["normal", "fighting"] },
  steel: { strong: ["ice", "rock", "fairy"], weak: ["fire", "fighting", "ground"] },
  normal: { strong: [], weak: ["fighting"], immune: ["ghost"] },
};
